// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/pb/api.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.

type ChannelID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelID) Reset()         { *m = ChannelID{} }
func (m *ChannelID) String() string { return proto.CompactTextString(m) }
func (*ChannelID) ProtoMessage()    {}
func (*ChannelID) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d5f8b3ab148d35, []int{0}
}

func (m *ChannelID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelID.Unmarshal(m, b)
}
func (m *ChannelID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelID.Marshal(b, m, deterministic)
}
func (m *ChannelID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelID.Merge(m, src)
}
func (m *ChannelID) XXX_Size() int {
	return xxx_messageInfo_ChannelID.Size(m)
}
func (m *ChannelID) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelID.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelID proto.InternalMessageInfo

func (m *ChannelID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadSignal struct {
	MessageID            string   `protobuf:"bytes,1,opt,name=messageID,proto3" json:"messageID,omitempty"`
	ChannelID            string   `protobuf:"bytes,2,opt,name=channelID,proto3" json:"channelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadSignal) Reset()         { *m = ReadSignal{} }
func (m *ReadSignal) String() string { return proto.CompactTextString(m) }
func (*ReadSignal) ProtoMessage()    {}
func (*ReadSignal) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d5f8b3ab148d35, []int{1}
}

func (m *ReadSignal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSignal.Unmarshal(m, b)
}
func (m *ReadSignal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSignal.Marshal(b, m, deterministic)
}
func (m *ReadSignal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSignal.Merge(m, src)
}
func (m *ReadSignal) XXX_Size() int {
	return xxx_messageInfo_ReadSignal.Size(m)
}
func (m *ReadSignal) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSignal.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSignal proto.InternalMessageInfo

func (m *ReadSignal) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func (m *ReadSignal) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

type Messages struct {
	Msg                  []*Message `protobuf:"bytes,1,rep,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Messages) Reset()         { *m = Messages{} }
func (m *Messages) String() string { return proto.CompactTextString(m) }
func (*Messages) ProtoMessage()    {}
func (*Messages) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d5f8b3ab148d35, []int{2}
}

func (m *Messages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Messages.Unmarshal(m, b)
}
func (m *Messages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Messages.Marshal(b, m, deterministic)
}
func (m *Messages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Messages.Merge(m, src)
}
func (m *Messages) XXX_Size() int {
	return xxx_messageInfo_Messages.Size(m)
}
func (m *Messages) XXX_DiscardUnknown() {
	xxx_messageInfo_Messages.DiscardUnknown(m)
}

var xxx_messageInfo_Messages proto.InternalMessageInfo

func (m *Messages) GetMsg() []*Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Channels struct {
	Msg                  []*Channel `protobuf:"bytes,1,rep,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Channels) Reset()         { *m = Channels{} }
func (m *Channels) String() string { return proto.CompactTextString(m) }
func (*Channels) ProtoMessage()    {}
func (*Channels) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d5f8b3ab148d35, []int{3}
}

func (m *Channels) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channels.Unmarshal(m, b)
}
func (m *Channels) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channels.Marshal(b, m, deterministic)
}
func (m *Channels) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channels.Merge(m, src)
}
func (m *Channels) XXX_Size() int {
	return xxx_messageInfo_Channels.Size(m)
}
func (m *Channels) XXX_DiscardUnknown() {
	xxx_messageInfo_Channels.DiscardUnknown(m)
}

var xxx_messageInfo_Channels proto.InternalMessageInfo

func (m *Channels) GetMsg() []*Channel {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Channel struct {
	Members              []string          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string            `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Roles                map[string]string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ChannelId            string            `protobuf:"bytes,5,opt,name=channelId,proto3" json:"channelId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d5f8b3ab148d35, []int{4}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Channel) GetRoles() map[string]string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Channel) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type Event struct {
	// Types that are valid to be assigned to Event:
	//	*Event_Dlv
	//	*Event_Read
	//	*Event_Keep
	//	*Event_NewMessage
	//	*Event_Join
	Event                isEvent_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d5f8b3ab148d35, []int{5}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

type isEvent_Event interface {
	isEvent_Event()
}

type Event_Dlv struct {
	Dlv *DeliveredSignal `protobuf:"bytes,1,opt,name=dlv,proto3,oneof"`
}

type Event_Read struct {
	Read *ReadSignal `protobuf:"bytes,2,opt,name=read,proto3,oneof"`
}

type Event_Keep struct {
	Keep *KeepAliveSignal `protobuf:"bytes,3,opt,name=keep,proto3,oneof"`
}

type Event_NewMessage struct {
	NewMessage *Message `protobuf:"bytes,5,opt,name=newMessage,proto3,oneof"`
}

type Event_Join struct {
	Join *JoinSignal `protobuf:"bytes,6,opt,name=join,proto3,oneof"`
}

func (*Event_Dlv) isEvent_Event() {}

func (*Event_Read) isEvent_Event() {}

func (*Event_Keep) isEvent_Event() {}

func (*Event_NewMessage) isEvent_Event() {}

func (*Event_Join) isEvent_Event() {}

func (m *Event) GetEvent() isEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Event) GetDlv() *DeliveredSignal {
	if x, ok := m.GetEvent().(*Event_Dlv); ok {
		return x.Dlv
	}
	return nil
}

func (m *Event) GetRead() *ReadSignal {
	if x, ok := m.GetEvent().(*Event_Read); ok {
		return x.Read
	}
	return nil
}

func (m *Event) GetKeep() *KeepAliveSignal {
	if x, ok := m.GetEvent().(*Event_Keep); ok {
		return x.Keep
	}
	return nil
}

func (m *Event) GetNewMessage() *Message {
	if x, ok := m.GetEvent().(*Event_NewMessage); ok {
		return x.NewMessage
	}
	return nil
}

func (m *Event) GetJoin() *JoinSignal {
	if x, ok := m.GetEvent().(*Event_Join); ok {
		return x.Join
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Event) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Event_Dlv)(nil),
		(*Event_Read)(nil),
		(*Event_Keep)(nil),
		(*Event_NewMessage)(nil),
		(*Event_Join)(nil),
	}
}

type Empty struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d5f8b3ab148d35, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func (m *Empty) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type KeepAliveSignal struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveSignal) Reset()         { *m = KeepAliveSignal{} }
func (m *KeepAliveSignal) String() string { return proto.CompactTextString(m) }
func (*KeepAliveSignal) ProtoMessage()    {}
func (*KeepAliveSignal) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d5f8b3ab148d35, []int{7}
}

func (m *KeepAliveSignal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveSignal.Unmarshal(m, b)
}
func (m *KeepAliveSignal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveSignal.Marshal(b, m, deterministic)
}
func (m *KeepAliveSignal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveSignal.Merge(m, src)
}
func (m *KeepAliveSignal) XXX_Size() int {
	return xxx_messageInfo_KeepAliveSignal.Size(m)
}
func (m *KeepAliveSignal) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveSignal.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveSignal proto.InternalMessageInfo

type DeliveredSignal struct {
	MessageID            string   `protobuf:"bytes,1,opt,name=messageID,proto3" json:"messageID,omitempty"`
	ChannelID            string   `protobuf:"bytes,2,opt,name=channelID,proto3" json:"channelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliveredSignal) Reset()         { *m = DeliveredSignal{} }
func (m *DeliveredSignal) String() string { return proto.CompactTextString(m) }
func (*DeliveredSignal) ProtoMessage()    {}
func (*DeliveredSignal) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d5f8b3ab148d35, []int{8}
}

func (m *DeliveredSignal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveredSignal.Unmarshal(m, b)
}
func (m *DeliveredSignal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveredSignal.Marshal(b, m, deterministic)
}
func (m *DeliveredSignal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveredSignal.Merge(m, src)
}
func (m *DeliveredSignal) XXX_Size() int {
	return xxx_messageInfo_DeliveredSignal.Size(m)
}
func (m *DeliveredSignal) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveredSignal.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveredSignal proto.InternalMessageInfo

func (m *DeliveredSignal) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func (m *DeliveredSignal) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

type JoinSignal struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinSignal) Reset()         { *m = JoinSignal{} }
func (m *JoinSignal) String() string { return proto.CompactTextString(m) }
func (*JoinSignal) ProtoMessage()    {}
func (*JoinSignal) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d5f8b3ab148d35, []int{9}
}

func (m *JoinSignal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinSignal.Unmarshal(m, b)
}
func (m *JoinSignal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinSignal.Marshal(b, m, deterministic)
}
func (m *JoinSignal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinSignal.Merge(m, src)
}
func (m *JoinSignal) XXX_Size() int {
	return xxx_messageInfo_JoinSignal.Size(m)
}
func (m *JoinSignal) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinSignal.DiscardUnknown(m)
}

var xxx_messageInfo_JoinSignal proto.InternalMessageInfo

func (m *JoinSignal) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type UserDiscoveryEvent struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ChannelID            string   `protobuf:"bytes,2,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDiscoveryEvent) Reset()         { *m = UserDiscoveryEvent{} }
func (m *UserDiscoveryEvent) String() string { return proto.CompactTextString(m) }
func (*UserDiscoveryEvent) ProtoMessage()    {}
func (*UserDiscoveryEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d5f8b3ab148d35, []int{10}
}

func (m *UserDiscoveryEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDiscoveryEvent.Unmarshal(m, b)
}
func (m *UserDiscoveryEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDiscoveryEvent.Marshal(b, m, deterministic)
}
func (m *UserDiscoveryEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDiscoveryEvent.Merge(m, src)
}
func (m *UserDiscoveryEvent) XXX_Size() int {
	return xxx_messageInfo_UserDiscoveryEvent.Size(m)
}
func (m *UserDiscoveryEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDiscoveryEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UserDiscoveryEvent proto.InternalMessageInfo

func (m *UserDiscoveryEvent) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserDiscoveryEvent) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

type Message struct {
	MessageType          string   `protobuf:"bytes,1,opt,name=messageType,proto3" json:"messageType,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Channel              string   `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	To                   string   `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Body                 string   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	SessionID            string   `protobuf:"bytes,6,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	MessageID            string   `protobuf:"bytes,7,opt,name=messageID,proto3" json:"messageID,omitempty"`
	ChannelID            string   `protobuf:"bytes,8,opt,name=channelID,proto3" json:"channelID,omitempty"`
	Time                 string   `protobuf:"bytes,9,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d5f8b3ab148d35, []int{11}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

func (m *Message) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Message) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *Message) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Message) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Message) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *Message) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func (m *Message) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *Message) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func init() {
	proto.RegisterType((*ChannelID)(nil), "channelID")
	proto.RegisterType((*ReadSignal)(nil), "ReadSignal")
	proto.RegisterType((*Messages)(nil), "Messages")
	proto.RegisterType((*Channels)(nil), "Channels")
	proto.RegisterType((*Channel)(nil), "Channel")
	proto.RegisterMapType((map[string]string)(nil), "Channel.RolesEntry")
	proto.RegisterType((*Event)(nil), "Event")
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*KeepAliveSignal)(nil), "KeepAliveSignal")
	proto.RegisterType((*DeliveredSignal)(nil), "DeliveredSignal")
	proto.RegisterType((*JoinSignal)(nil), "JoinSignal")
	proto.RegisterType((*UserDiscoveryEvent)(nil), "UserDiscoveryEvent")
	proto.RegisterType((*Message)(nil), "Message")
}

func init() { proto.RegisterFile("api/pb/api.proto", fileDescriptor_73d5f8b3ab148d35) }

var fileDescriptor_73d5f8b3ab148d35 = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0x13, 0xdb, 0xa9, 0x27, 0x88, 0x86, 0x05, 0x45, 0x56, 0x40, 0x6a, 0x6a, 0x41, 0x15,
	0x7a, 0x70, 0x51, 0xb8, 0x54, 0xdc, 0x68, 0x1d, 0x91, 0x14, 0x7a, 0x31, 0xf0, 0x00, 0x4e, 0x3c,
	0x49, 0x97, 0xda, 0x5e, 0xcb, 0xeb, 0x04, 0xf9, 0xa9, 0x78, 0x13, 0xc4, 0x7b, 0xf0, 0x12, 0x68,
	0xd7, 0xeb, 0x9f, 0x04, 0x89, 0x0b, 0x27, 0xcf, 0x7c, 0xf3, 0xed, 0xfc, 0x8f, 0x61, 0x10, 0xa4,
	0xf4, 0x32, 0x5d, 0x5e, 0x06, 0x29, 0x75, 0xd3, 0x8c, 0xe5, 0xcc, 0x79, 0x0e, 0xd6, 0xea, 0x3e,
	0x48, 0x12, 0x8c, 0x16, 0x1e, 0x79, 0x0c, 0x1d, 0x1a, 0xda, 0xda, 0x58, 0x9b, 0x58, 0x7e, 0x87,
	0x86, 0xce, 0x1c, 0xc0, 0xc7, 0x20, 0xfc, 0x4c, 0x37, 0x49, 0x10, 0x91, 0x17, 0x60, 0xc5, 0xc8,
	0x79, 0xb0, 0xc1, 0x85, 0xa7, 0x48, 0x0d, 0x20, 0xac, 0xb5, 0x23, 0xbb, 0x53, 0x5a, 0x6b, 0xc0,
	0x39, 0x87, 0xe3, 0xbb, 0x92, 0xca, 0xc9, 0x08, 0xba, 0x31, 0xdf, 0xd8, 0xda, 0xb8, 0x3b, 0xe9,
	0x4f, 0x8f, 0x5d, 0x85, 0xfb, 0x02, 0x14, 0xbc, 0x9b, 0xf2, 0xd1, 0x5f, 0x3c, 0x85, 0x97, 0xbc,
	0x9f, 0x1a, 0xf4, 0x14, 0x40, 0x6c, 0xe8, 0xc5, 0x18, 0x2f, 0x31, 0xe3, 0x92, 0x6b, 0xf9, 0x95,
	0x4a, 0x08, 0xe8, 0x49, 0x10, 0xa3, 0x4a, 0x47, 0xca, 0x02, 0xcb, 0x8b, 0x14, 0xed, 0x6e, 0x89,
	0x09, 0x99, 0xbc, 0x06, 0x23, 0x63, 0x11, 0x72, 0x5b, 0x97, 0xb1, 0x9e, 0x56, 0xb1, 0x5c, 0x5f,
	0xa0, 0xb3, 0x24, 0xcf, 0x0a, 0xbf, 0x64, 0xb4, 0xcb, 0x0c, 0x6d, 0x63, 0xbf, 0xcc, 0x70, 0x74,
	0x05, 0xd0, 0x3c, 0x21, 0x03, 0xe8, 0x3e, 0x60, 0xa1, 0x5a, 0x25, 0x44, 0xf2, 0x0c, 0x8c, 0x5d,
	0x10, 0x6d, 0xab, 0x8c, 0x4a, 0xe5, 0x5d, 0xe7, 0x4a, 0x73, 0x7e, 0x69, 0x60, 0xcc, 0x76, 0x98,
	0xe4, 0xe4, 0x25, 0x74, 0xc3, 0x68, 0x27, 0x5f, 0xf5, 0xa7, 0x03, 0xd7, 0xc3, 0x88, 0xee, 0x30,
	0x43, 0x35, 0x85, 0xf9, 0x91, 0x2f, 0xcc, 0xe4, 0x0c, 0xf4, 0x0c, 0x83, 0x50, 0x3a, 0xea, 0x4f,
	0xfb, 0x6e, 0x33, 0xa7, 0xf9, 0x91, 0x2f, 0x4d, 0xe4, 0x1c, 0xf4, 0x07, 0xc4, 0x54, 0x56, 0x2a,
	0x3c, 0x7d, 0x44, 0x4c, 0xdf, 0x0b, 0x67, 0x0d, 0x4f, 0xd8, 0xc9, 0x05, 0x40, 0x82, 0xdf, 0xd5,
	0x18, 0x64, 0x4d, 0xad, 0xb1, 0xcc, 0x8f, 0xfc, 0x96, 0x55, 0x84, 0xfd, 0xc6, 0x68, 0x62, 0x9b,
	0x2a, 0xec, 0x2d, 0xa3, 0x49, 0xe3, 0x4e, 0x98, 0xae, 0x7b, 0x60, 0xa0, 0x28, 0xc4, 0x39, 0x05,
	0x63, 0x16, 0xa7, 0x79, 0x41, 0x86, 0x60, 0xf2, 0x3c, 0xc8, 0xb7, 0x5c, 0xb5, 0x42, 0x69, 0xce,
	0x13, 0x38, 0x39, 0xc8, 0xc9, 0xb9, 0x83, 0x93, 0x83, 0x82, 0xff, 0x6b, 0xed, 0x2e, 0x00, 0x9a,
	0x0c, 0x05, 0x97, 0x23, 0xe7, 0x94, 0x25, 0x8b, 0x6a, 0xcb, 0x1b, 0xc0, 0xb9, 0x05, 0xf2, 0x95,
	0x63, 0xe6, 0x51, 0xbe, 0x62, 0x3b, 0xcc, 0x8a, 0x72, 0x1a, 0x43, 0x30, 0x05, 0x5a, 0x87, 0x56,
	0x9a, 0xf0, 0x75, 0x73, 0x18, 0xb7, 0x06, 0x9c, 0xdf, 0x1a, 0xf4, 0xaa, 0x96, 0x8d, 0xa1, 0xaf,
	0xd2, 0xfd, 0x22, 0xf6, 0xae, 0x74, 0xd3, 0x86, 0xc4, 0x4a, 0xae, 0x33, 0x16, 0x57, 0x6b, 0x2a,
	0x64, 0xb1, 0xd4, 0xaa, 0x0c, 0xb5, 0xa9, 0x95, 0x2a, 0x8e, 0x34, 0x67, 0xb6, 0x5e, 0x1e, 0x69,
	0xce, 0xc4, 0xeb, 0x25, 0x0b, 0x0b, 0xb5, 0x8c, 0x52, 0x6e, 0x57, 0xea, 0xc9, 0x59, 0xb5, 0x2a,
	0xf5, 0xf6, 0x3b, 0xda, 0xfb, 0x67, 0x47, 0x8f, 0x0f, 0x3a, 0x2a, 0xcf, 0x87, 0xc6, 0x68, 0x5b,
	0xea, 0x7c, 0x68, 0x8c, 0xd3, 0x1f, 0x1a, 0x98, 0x73, 0xcc, 0x62, 0xe4, 0xe4, 0x14, 0x2c, 0xd9,
	0xb7, 0xeb, 0xed, 0x7a, 0x4d, 0x4c, 0x57, 0xca, 0x23, 0xf5, 0x9d, 0x68, 0x6f, 0x34, 0x72, 0x06,
	0x8f, 0x3e, 0x51, 0x9e, 0xd7, 0x47, 0x6e, 0xba, 0x72, 0x47, 0x46, 0x96, 0x5b, 0x43, 0xaf, 0x4a,
	0x4a, 0xfd, 0xbf, 0x00, 0xb7, 0x0e, 0x3f, 0xb2, 0xdc, 0x1a, 0x76, 0x00, 0x3e, 0x60, 0xe5, 0x68,
	0x8f, 0x54, 0xff, 0x2b, 0xc8, 0x10, 0xf4, 0xd9, 0xea, 0x9e, 0xd5, 0x51, 0xd4, 0x77, 0x69, 0xca,
	0x9f, 0xdf, 0xdb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x26, 0x7e, 0x3d, 0xd5, 0x10, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HermesClient is the client API for Hermes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HermesClient interface {
	EventBuff(ctx context.Context, opts ...grpc.CallOption) (Hermes_EventBuffClient, error)
	ListChannels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Channels, error)
	ListMessages(ctx context.Context, in *ChannelID, opts ...grpc.CallOption) (*Messages, error)
	GetChannel(ctx context.Context, in *ChannelID, opts ...grpc.CallOption) (*Channel, error)
	Echo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type hermesClient struct {
	cc *grpc.ClientConn
}

func NewHermesClient(cc *grpc.ClientConn) HermesClient {
	return &hermesClient{cc}
}

func (c *hermesClient) EventBuff(ctx context.Context, opts ...grpc.CallOption) (Hermes_EventBuffClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Hermes_serviceDesc.Streams[0], "/Hermes/EventBuff", opts...)
	if err != nil {
		return nil, err
	}
	x := &hermesEventBuffClient{stream}
	return x, nil
}

type Hermes_EventBuffClient interface {
	Send(*Event) error
	Recv() (*Event, error)
	grpc.ClientStream
}

type hermesEventBuffClient struct {
	grpc.ClientStream
}

func (x *hermesEventBuffClient) Send(m *Event) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hermesEventBuffClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hermesClient) ListChannels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Channels, error) {
	out := new(Channels)
	err := c.cc.Invoke(ctx, "/Hermes/ListChannels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hermesClient) ListMessages(ctx context.Context, in *ChannelID, opts ...grpc.CallOption) (*Messages, error) {
	out := new(Messages)
	err := c.cc.Invoke(ctx, "/Hermes/ListMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hermesClient) GetChannel(ctx context.Context, in *ChannelID, opts ...grpc.CallOption) (*Channel, error) {
	out := new(Channel)
	err := c.cc.Invoke(ctx, "/Hermes/GetChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hermesClient) Echo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Hermes/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HermesServer is the server API for Hermes service.
type HermesServer interface {
	EventBuff(Hermes_EventBuffServer) error
	ListChannels(context.Context, *Empty) (*Channels, error)
	ListMessages(context.Context, *ChannelID) (*Messages, error)
	GetChannel(context.Context, *ChannelID) (*Channel, error)
	Echo(context.Context, *Empty) (*Empty, error)
}

// UnimplementedHermesServer can be embedded to have forward compatible implementations.
type UnimplementedHermesServer struct {
}

func (*UnimplementedHermesServer) EventBuff(srv Hermes_EventBuffServer) error {
	return status.Errorf(codes.Unimplemented, "method EventBuff not implemented")
}
func (*UnimplementedHermesServer) ListChannels(ctx context.Context, req *Empty) (*Channels, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChannels not implemented")
}
func (*UnimplementedHermesServer) ListMessages(ctx context.Context, req *ChannelID) (*Messages, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMessages not implemented")
}
func (*UnimplementedHermesServer) GetChannel(ctx context.Context, req *ChannelID) (*Channel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChannel not implemented")
}
func (*UnimplementedHermesServer) Echo(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}

func RegisterHermesServer(s *grpc.Server, srv HermesServer) {
	s.RegisterService(&_Hermes_serviceDesc, srv)
}

func _Hermes_EventBuff_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HermesServer).EventBuff(&hermesEventBuffServer{stream})
}

type Hermes_EventBuffServer interface {
	Send(*Event) error
	Recv() (*Event, error)
	grpc.ServerStream
}

type hermesEventBuffServer struct {
	grpc.ServerStream
}

func (x *hermesEventBuffServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hermesEventBuffServer) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Hermes_ListChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesServer).ListChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hermes/ListChannels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesServer).ListChannels(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hermes_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hermes/ListMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesServer).ListMessages(ctx, req.(*ChannelID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hermes_GetChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesServer).GetChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hermes/GetChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesServer).GetChannel(ctx, req.(*ChannelID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hermes_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hermes/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesServer).Echo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hermes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Hermes",
	HandlerType: (*HermesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListChannels",
			Handler:    _Hermes_ListChannels_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _Hermes_ListMessages_Handler,
		},
		{
			MethodName: "GetChannel",
			Handler:    _Hermes_GetChannel_Handler,
		},
		{
			MethodName: "Echo",
			Handler:    _Hermes_Echo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventBuff",
			Handler:       _Hermes_EventBuff_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/pb/api.proto",
}
