// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ChannelMembers     string
	ChannelPermissions string
	Channels           string
	Messages           string
	Migrations         string
	Roles              string
	UserRole           string
	Users              string
}{
	ChannelMembers:     "channel_members",
	ChannelPermissions: "channel_permissions",
	Channels:           "channels",
	Messages:           "messages",
	Migrations:         "migrations",
	Roles:              "roles",
	UserRole:           "user_role",
	Users:              "users",
}
