// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("ChannelMembers", testChannelMembersUpsert)

	t.Run("ChannelPermissions", testChannelPermissionsUpsert)

	t.Run("Channels", testChannelsUpsert)

	t.Run("Messages", testMessagesUpsert)

	t.Run("Migrations", testMigrationsUpsert)

	t.Run("Roles", testRolesUpsert)

	t.Run("UserRoles", testUserRolesUpsert)

	t.Run("Users", testUsersUpsert)
}
